development:
  adapter: postgresql
  database: uni_production
  pool: 5
  timeout: 5000
  username: pawelgraczyk
  password:
  host: localhost

#development:
#  adapter: postgresql
#  database: uni_production
#  pool: 5
#  timeout: 5000
#  username: uni
#  password: uni#db
#  host: localhost

test: &test
  adapter: postgresql
  database: db/testpg
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: uni_production
  host: localhost
  port: 5432
  pool: 5
  username: uni
  password: uni#db
