development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: uni_production
  host: 127.0.0.1
  port: 5432
  pool: 5
  username: uni
  password: uni#db
